# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  pull_request:
    branches: main

name: cicd

jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::pkgdown
            local::.
          needs: |
            check
            website

      - uses: r-lib/actions/check-r-package@v2

      - name: Update data
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        env:
          HOADDATA_PASSWORD: ${{ secrets.HOADDATA_PASSWORD }}
        run: |
          source("data-raw/jct_001_get_cr_data.R")
        shell: Rscript {0}
      
      - name: Check package after data update
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: r-lib/actions/check-r-package@v2
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          base: main
          branch: ${{ env.BRANCH_NAME }}
          commit-message: "Data update: ${{ github.event.repository.updated_at}}"
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          title: 'Update data'
          body: |
            This PR updates the data.
            
            Data update: ${{ github.event.repository.updated_at}}

            Changelog:

            ${{steps.build_changelog.outputs.changelog}}
          labels: |
            data
            automated pr
          assignees: njahn82
          reviewers: njahn82

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
